# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '質問', 'verbose_name_plural': '質問の複数形'},
        ),
    ]
