# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160517_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pub_date'], 'verbose_name': '質問', 'verbose_name_plural': '質問の複数形'},
        ),
    ]
